In [1]:
import numpy as np
a1=np.array([[2,3,5,6],[3,6,7,3]])
print(a1)
print()
print(a1.ndim)
print()
print(a1.shape)
print()
print(a1.data)
print()
print(type(a1))

[[2 3 5 6]
 [3 6 7 3]]

2

(2, 4)


<class 'numpy.ndarray'>


In [2]:
b1=np.array([[78,45,62],[89,5,4]],dtype=np.float64)
print(b1)
print()
print(b1.dtype)
print(type(b1))
print(b1.size)
print(b1.ndim)
print(b1.shape)
print(b1.itemsize)

[[78. 45. 62.]
 [89.  5.  4.]]

float64
<class 'numpy.ndarray'>
6
2
(2, 3)
8


In [3]:
c1=np.array(["l","a"])
print(c1.dtype)
print(c1.size)
print(c1.itemsize)
print(c1.shape)

<U1
2
4
(2,)


In [4]:
b1=np.array([[78,45,62],[89,5,4]],dtype=np.complex64)

print(b1)
print()
print(b1.dtype)
print()
print(b1.itemsize)
print()
print(b1.size)
b1=np.array([[78,45,62],[89,5,4]],dtype=np.complex128)
print(b1)
print()
print(b1.dtype)
print()
print(b1.itemsize)
print()
print(b1.size)

[[78.+0.j 45.+0.j 62.+0.j]
 [89.+0.j  5.+0.j  4.+0.j]]

complex64

8

6
[[78.+0.j 45.+0.j 62.+0.j]
 [89.+0.j  5.+0.j  4.+0.j]]

complex128

16

6


In [5]:
b1=np.array([[78,45,62],[89,5,4]],dtype=np.float64)
print(b1)


[[78. 45. 62.]
 [89.  5.  4.]]


In [6]:
print(np.sum(b1,axis=0))#col
print(np.sum(b1,axis=1))#row

[167.  50.  66.]
[185.  98.]


In [7]:
print(np.amin(b1))#min value
print(np.amin(b1,axis=0))
print(np.amin(b1,axis=1))

4.0
[78.  5.  4.]
[45.  4.]


In [8]:
print(np.amax(b1))#max value
print(np.amax(b1,axis=0))
print(np.amax(b1,axis=1))

89.0
[89. 45. 62.]
[78. 89.]


In [9]:
print(np.mean(b1))#mean value
print(np.mean(b1,axis=0))
print(np.mean(b1,axis=1))
print()
print(np.average(b1))#avg value
print(np.average(b1,axis=0))
print(np.average(b1,axis=1))


47.166666666666664
[83.5 25.  33. ]
[61.66666667 32.66666667]

47.166666666666664
[83.5 25.  33. ]
[61.66666667 32.66666667]


In [10]:
print(np.std(b1))#std value
print(np.std(b1,axis=0))
print(np.std(b1,axis=1))

33.08280856006972
[ 5.5 20.  29. ]
[13.47425529 39.83577398]


In [11]:
print(np.var(b1))#var value
print(np.var(b1,axis=0))
print(np.var(b1,axis=1))

1094.4722222222224
[ 30.25 400.   841.  ]
[ 181.55555556 1586.88888889]


In [12]:
print(np.median(b1))#median value
print(np.median(b1,axis=0))
print(np.median(b1,axis=1))

53.5
[83.5 25.  33. ]
[62.  5.]


In [13]:
array=np.array([3,5,3,6,8,9,4])
w1=np.array([4.6,5.9,3.5,3.6,7.6,4.5,9.43])
n=np.average(array,weights=w1)
print(n)

5.479683107590084


In [14]:
print(np.percentile(array,7.8))
print()
print(np.percentile(b1,7.8,1))
print()
print(np.percentile(b1,7.8,0))
print()
print(b1)

3.0

[47.652  4.156]

[78.858  8.12   8.524]

[[78. 45. 62.]
 [89.  5.  4.]]


In [15]:
print(array)
print()
print(b1)
print()
print(np.ptp(array,0))
print(np.ptp(b1,0))
print(np.ptp(b1,1))

[3 5 3 6 8 9 4]

[[78. 45. 62.]
 [89.  5.  4.]]

6
[11. 40. 58.]
[33. 85.]


In [16]:
A1=np.array([[56,75,34,23],[4,7,3,2]])
print(A1.shape)
print()
print(A1)
print()
print(A1.reshape(4,2))

(2, 4)

[[56 75 34 23]
 [ 4  7  3  2]]

[[56 75]
 [34 23]
 [ 4  7]
 [ 3  2]]


In [17]:
#slicing
l=np.array([[34,56,78,95],[98,34,89,54],[39,89,45,65]])
print(l)
print()
print(l[0,3])

[[34 56 78 95]
 [98 34 89 54]
 [39 89 45 65]]

95
